eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  devtools:
    restart:
      enabled: true
      exclude: resources/** #devtool热加载工具
      
 # 配置环境
env:
  test-come-on
  
# 测试配置前缀
nba:
  name: tomas
  champion: 1
