eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: service-ask
  devtools:
    restart:
      enabled: true
      exclude: resources/** #devtool热加载工具
      
 # 配置环境
env:
  dev
