eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  devtools:
    restart:
      enabled: true
      exclude: resources/** #devtool热加载工具
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest    
      
 # 配置环境
env:
  test
  
# 测试配置前缀
nba:
  name: never give up
  champion: 55
